services:
  pz-sticker-api:
    build: .
    container_name: pz-sticker-api
    network_mode: host
    environment:
      - APP_PORT=8189
    env_file:
      - .env
    volumes:
      - ./work_dir:/app/work_dir
    restart: unless-stopped
