version: "3.8"

services:
  pz-sticker-api:
    build: .
    container_name: pz-sticker-api
    ports:
      - "8188:8188"
    env_file:
      - .env
    volumes:
      - ./work_dir:/app/work_dir
    restart: unless-stopped
